services:
  telegram-bot:
    build:
      context: .
      shm_size: "256m"
    env_file:
      - .env
    container_name: tg_rag
    command: python src/main.py
    restart: unless-stopped
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 700M
          cpus: "0.6"